# Generated by Django 3.2 on 2024-10-26 07:16

import datetime
from django.db import migrations, models

utc = datetime.timezone.utc  # Use Python's datetime module directly for UTC

class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0039_alter_sub_admindt_subadmin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(
                blank=True, default='2b44f4c8', max_length=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_last_login',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 27, 7, 16, 0, 470143, tzinfo=utc),
                verbose_name='last login',
            ),
        ),
    ]
