# Generated by Django 5.0.6 on 2024-10-26 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0040_auto_20241026_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(blank=True, default='b2292c22', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 7, 28, 24, 439555, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
