# Generated by Django 5.0.6 on 2024-12-28 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0061_alter_sub_admindt_subadmin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_admindt',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sub_admindt',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(blank=True, default='c270172a', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 11, 5, 53, 577820, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
