# Generated by Django 5.0.6 on 2025-02-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0078_sub_admindt_sub_admin_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(blank=True, default='4fffac9f', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 7, 18, 780948, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
