# Generated by Django 5.0.4 on 2024-10-22 05:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_SYMBOL_QTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('SYMBOL', models.CharField(blank=True, max_length=50, null=True)),
                ('QUANTITY', models.FloatField(blank=True, null=True)),
                ('trade', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_admin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('clint_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('clint_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clint_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('login_date_time', models.DateTimeField(blank=True, null=True)),
                ('panel_last_login', models.DateTimeField(blank=True, null=True)),
                ('clint_plane', models.CharField(blank=True, max_length=15, null=True)),
                ('trading', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('client_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT4Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MT5OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('client_login', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strategy', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('price_open', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price_current', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sl', models.DecimalField(decimal_places=5, max_digits=10)),
                ('tp', models.DecimalField(decimal_places=5, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='0533c495', max_length=8, unique=True)),
                ('user_active', models.BooleanField(default=False)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=15, null=True)),
                ('date_joined', models.DateTimeField(default=None, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=None, verbose_name='last login')),
                ('panel_last_login', models.DateTimeField(blank=True, null=True)),
                ('clint_plane', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('clint_status', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('mt5_login', models.IntegerField(blank=True, null=True)),
                ('mt5_password', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('demo', 'Demo'), ('live', 'Live')], default='live', max_length=10)),
                ('sub_admin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_paln', models.BooleanField(blank=True, default=True, null=True)),
                ('Term_condition', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_option', models.CharField(choices=[('A', 'Route'), ('B', 'Detour'), ('C', 'Destination'), ('D', 'Demograph')], default='A', max_length=1)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.broker')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSymbolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trade_enabled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP', models.CharField(max_length=10)),
                ('min_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group'),
        ),
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail', to_field='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='national_ids/')),
                ('national_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id_issue_date', models.DateField(blank=True, null=True)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('reference_text', models.TextField(blank=True, null=True)),
                ('kyc_completed', models.BooleanField(default=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_verifications/')),
                ('video_verification_done', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='mt5_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_server', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='myapp.broker')),
            ],
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='mt5_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mt5_server'),
        ),
        migrations.CreateModel(
            name='SYMBOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ids', models.CharField(blank=True, max_length=50, null=True)),
                ('TYPE', models.CharField(choices=[('BUY_ENTRY', 'BUY_ENTRY'), ('BUY_EXIT', 'BUY_EXIT'), ('SELL_ENTRY', 'SELL_ENTRY'), ('SELL_EXIT', 'SELL_EXIT')], max_length=10)),
                ('QUANTITY', models.FloatField(blank=True, null=True)),
                ('ENTRY_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('EXIT_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumulative_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SYMBOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_signals', to='myapp.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(max_length=50)),
                ('trade_type', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('p_l', models.FloatField(blank=True, null=True)),
                ('cumulative_p_l', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TradeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('status_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
    ]
