# Generated by Django 5.0.6 on 2024-12-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_clientdetail_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=50)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='offers_subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Offer_Title', models.CharField(max_length=200)),
                ('offer_price', models.IntegerField()),
                ('revenue', models.CharField(max_length=200)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='offers_images/')),
            ],
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='Bursa_Malaysia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='HK100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='Singapore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='US30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='comex_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='forex_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='mt5_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Route'), ('B', 'Detour'), ('C', 'Destination'), ('D', 'Demograph'), ('M', 'Messanger')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='3153304b', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('advisory_type', models.CharField(blank=True, choices=[('Forex', 'Forex'), ('Comex', 'Comex')], max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPaymetns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_admin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('payer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('pay_amount', models.IntegerField(blank=True, null=True)),
                ('offer_discount', models.IntegerField(blank=True, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_plan_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Initiated', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
