# Generated by Django 3.2 on 2024-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_clientdetail_mt5_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='675bb4f4', max_length=8, unique=True),
        ),
    ]
