# Generated by Django 5.0.6 on 2024-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='b19fb94e', max_length=8, unique=True),
        ),
    ]
