# Generated by Django 5.0.6 on 2024-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='fa395dd9', max_length=8, unique=True),
        ),
    ]
