# Generated by Django 5.0.6 on 2024-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_broker_broker_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=50)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='7cfbf11d', max_length=8, unique=True),
        ),
    ]
