# Generated by Django 5.0.6 on 2024-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_clientdetail_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Route'), ('B', 'Detour'), ('C', 'Destination'), ('D', 'Demograph'), ('M', 'Messanger')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='f9b5d08d', max_length=8, unique=True),
        ),
    ]
