# Generated by Django 5.0.6 on 2024-12-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_clientdetail_selected_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='comex_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='forex_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='advisory_type',
            field=models.CharField(blank=True, choices=[('Forex', 'Forex'), ('Comex', 'Comex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='1ea22252', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
