# Generated by Django 5.0.6 on 2024-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_clientdetail_comex_option_clientdetail_forex_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='ab18d5d4', max_length=8, unique=True),
        ),
    ]
