# Generated by Django 5.0.6 on 2024-12-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='Bursa_Malaysia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='HK100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='Singapore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='US30',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='0ea99046', max_length=8, unique=True),
        ),
    ]
