# Generated by Django 5.0.6 on 2024-12-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_clientdetail_bursa_malaysia_clientdetail_hk100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers_subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Offer_Title', models.CharField(max_length=200)),
                ('offer_price', models.IntegerField()),
                ('revenue', models.CharField(max_length=200)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='offers_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='ac428223', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ClientPaymetns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_admin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('payer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('pay_amount', models.IntegerField(blank=True, null=True)),
                ('offer_discount', models.IntegerField(blank=True, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_plan_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Initiated', max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.clientdetail')),
            ],
        ),
    ]
