# Generated by Django 5.0.6 on 2024-12-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marketdata_offers_subadmin_and_more'),
        ('myapp', '0020_alter_clientdetail_user_id'),
    ]

    operations = [
    ]
