# Generated by Django 5.0.6 on 2024-12-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_20241228_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpaymetns',
            name='client',
        ),
        migrations.DeleteModel(
            name='offers_subadmin',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.clientdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='205cd280', max_length=8, unique=True),
        ),
        migrations.DeleteModel(
            name='ClientPaymetns',
        ),
    ]
