# Generated by Django 5.0.6 on 2024-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_clientpaymetns_client_delete_offers_subadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='3f0648b9', max_length=8, unique=True),
        ),
    ]
