# Generated by Django 5.0.6 on 2024-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_clientdetail_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='ef3d73eb', max_length=8, unique=True),
        ),
    ]
