# Generated by Django 5.0.6 on 2024-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_clientdetail_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Route'), ('B', 'Detour'), ('C', 'Destination'), ('D', 'Demograph'), ('M', 'Messanger')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='ad16e4a7', max_length=8, unique=True),
        ),
    ]
