# Generated by Django 5.0.6 on 2024-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_clientdetail_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='ec17567f', max_length=8, unique=True),
        ),
    ]
