# Generated by Django 5.0.6 on 2024-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='73d2d0e3', max_length=8, unique=True),
        ),
    ]
