# Generated by Django 5.0.6 on 2024-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_offers_subadmin_alter_clientdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='4e493d45', max_length=8, unique=True),
        ),
    ]
