# Generated by Django 5.0.6 on 2025-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_clientdetail_user_id_alter_notification_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='sub_admin_user_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='5ab088e7', max_length=8, unique=True),
        ),
    ]
