# Generated by Django 5.0.6 on 2025-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_clientdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='662c1760', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpaymetns',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], default='PENDING', max_length=20),
        ),
    ]
