# Generated by Django 5.0.6 on 2025-01-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='7c544fef', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpaymetns',
            name='status',
            field=models.CharField(default='Initiated', max_length=20),
        ),
    ]
