# Generated by Django 5.0.6 on 2025-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_clientdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='95806b7b', max_length=8, unique=True),
        ),
    ]
