# Generated by Django 5.0.6 on 2025-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='6c8edb77', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpaymetns',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
