# Generated by Django 5.0.6 on 2025-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_clientdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='5f05de4b', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpaymetns',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
