# Generated by Django 5.0.4 on 2024-10-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forexadmin', '0037_alter_ind_admindt_admin_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ind_adminDT',
        ),
        migrations.DeleteModel(
            name='OrderAngelOne',
        ),
    ]
